# 47 - 에러 처리

**47.1 에러 처리의 필요성**

처리를 따로 하지 않으면 프로그램은 바로 강제종료됨 

**47.2 try...catch...finally 문**

try {

catch(error) {

}

finally {

}

**47.3 Error 객체**

const error = new Error(”error”);

message 프로퍼티와 statck 프로퍼티를 가짐 

message 프로퍼티의 값은 Error 생성자 함수에 인스로 전달한 에러 메세지

stack 프로퍼티의 값은 에러를 발생시킨 콜스택의 호출 정보를 나타냄 

Ex : SynstaxError : Invalid or unexpected token 

**47.4 throw 문**

에러를 발생시키려면 try 코드 블록에서 throw문으로 에러 객체를 던지기

throw new Error (”error”)

**47.5 에러의 전파**

에러는 호출자 방향으로 전파된다 

setInterval , 프로미스 후속 처리 매서드 : 실행 후에 호출자가 이미 없기 때문 

→ 콜 스택 비면 이동되어 실행될때 콜 스택에 푸시된 콜백 함수의 실행 컨텍스트는 콜 스택의 가장 하부에 존재 → 에러를 전파할 호출자가 존재하지 않음 

콜 스택의 아래 방향으로 전파된다. 

![스크린샷 2024-09-03 오후 2.01.48.png](47%20-%20%E1%84%8B%E1%85%A6%E1%84%85%E1%85%A5%20%E1%84%8E%E1%85%A5%E1%84%85%E1%85%B5%203a8759c111854e9cb09e30aad839a3dc/%25E1%2584%2589%25E1%2585%25B3%25E1%2584%258F%25E1%2585%25B3%25E1%2584%2585%25E1%2585%25B5%25E1%2586%25AB%25E1%2584%2589%25E1%2585%25A3%25E1%2586%25BA_2024-09-03_%25E1%2584%258B%25E1%2585%25A9%25E1%2584%2592%25E1%2585%25AE_2.01.48.png)